export const ADICCTIONS = [
  { id: 1, name: "Alcohol" },
  { id: 2, name: "Tabaco" },
  { id: 3, name: "Cannabis" },
  { id: 4, name: "Cocaína" },
  { id: 5, name: "Heroína" },
  { id: 6, name: "Metanfetaminas" },
  { id: 7, name: "Alucinógenos" },
  { id: 8, name: "Benzodiazepinas" },
  { id: 9, name: "Anfetaminas" },
  { id: 10, name: "Opioides recetados" },
  { id: 11, name: "Videojuegos" },
  { id: 12, name: "Apuestas (ludopatía)" },
  { id: 13, name: "Internet" },
  { id: 14, name: "Redes sociales" },
  { id: 15, name: "Pornografía" },
  { id: 16, name: "Comida" },
  { id: 17, name: "Café o bebidas con cafeína" },
  { id: 18, name: "Ejercicio compulsivo" },
  { id: 19, name: "Compras compulsivas" },
  { id: 20, name: "Trabajo (workaholism)" },
];
