export const FAKE_INTERNS = [
  {
    id: "clx1y2z3a45b6",
    created_at: "2025-01-01T12:00:00.000Z",
    name: "Carlos Pérez",
    birthdate: "1990-07-15T00:00:00.000Z",
    born_place: {
      departamento: "Lima",
      ciudad: "Lima",
    },
    isRural: false,
    cedula: 12345678,
    phone: "555-123-4567",
    references: [
      {
        name: "Luis Sánchez",
        phone: "555-987-6543",
        relationship: "Hermano",
      },
    ],
    marital_status: "Soltero",
    direction: {
      street: "Av. Principal 123",
      zone: "Centro",
      city: "Lima",
    },
    adiccions: [
      {
        name: "Alcohol",
        consumption_time: "5 años",
      },
    ],
    education: {
      primary: true,
      secondary: true,
      university: false,
    },
    profession: "Electricista",
    ocupation: "Técnico",
    talents: ["Carpintería", "Mecánica"],
    guarantor_name: "Rosa Martínez",
    image: null,
    user_id: "user123",
    interned_at: "2025-01-05T10:00:00.000Z",
    out_at: null,
    status: "Activo",
    finished_program: false,
    out_properties: null,
  },
  {
    id: "clx1y2z3a45b7",
    created_at: "2025-01-02T14:30:00.000Z",
    name: "María López",
    birthdate: "1985-03-22T00:00:00.000Z",
    born_place: {
      departamento: "Cajamarca",
      ciudad: "Jaén",
    },
    isRural: true,
    cedula: 87654321,
    phone: "555-654-3210",
    references: [
      {
        name: "Ana Torres",
        phone: "555-321-9870",
        relationship: "Amiga",
      },
      {
        name: "Juan López",
        phone: "555-789-0123",
        relationship: "Hermano",
      },
    ],
    marital_status: "Casada",
    direction: {
      street: "Calle Los Olivos 45",
      zone: "Sur",
      city: "Jaén",
    },
    adiccions: [
      {
        name: "Tabaco",
        consumption_time: "10 años",
      },
    ],
    education: {
      primary: true,
      secondary: true,
      university: true,
    },
    profession: "Contadora",
    ocupation: "Administradora",
    talents: ["Pintura", "Cocina"],
    guarantor_name: "José Fernández",
    image: null,
    user_id: "user124",
    interned_at: "2025-01-10T09:30:00.000Z",
    out_at: "2025-01-20T17:00:00.000Z",
    status: "Inactivo",
    finished_program: true,
    out_properties: {
      reason: "Alta voluntaria",
      observations: "Paciente completó el programa satisfactoriamente.",
    },
  },
  {
    id: "clx2a3b4c56d7",
    created_at: "2024-12-01T08:45:00.000Z",
    name: "Pedro Alvarado",
    birthdate: "1975-11-20T00:00:00.000Z",
    born_place: {
      departamento: "Cusco",
      ciudad: "Urubamba",
    },
    isRural: true,
    cedula: 54321678,
    phone: "555-998-7766",
    references: [
      {
        name: "Sonia Quispe",
        phone: "555-887-7765",
        relationship: "Esposa",
      },
    ],
    marital_status: "Casado",
    direction: {
      street: "Calle Puno 12",
      zone: "Norte",
      city: "Urubamba",
    },
    adiccions: [
      {
        name: "Alcohol",
        consumption_time: "15 años",
      },
      {
        name: "Tabaco",
        consumption_time: "8 años",
      },
    ],
    education: {
      primary: true,
      secondary: false,
      university: false,
    },
    profession: "Agricultor",
    ocupation: "Campesino",
    talents: ["Cuidado de animales", "Carpintería"],
    guarantor_name: "Miguel Alvarado",
    image: null,
    user_id: "user125",
    interned_at: "2024-12-15T10:00:00.000Z",
    out_at: null,
    status: "Activo",
    finished_program: false,
    out_properties: null,
  },
  {
    id: "clx2a3b4c56d8",
    created_at: "2023-06-15T11:30:00.000Z",
    name: "Ana Rojas",
    birthdate: "1995-05-12T00:00:00.000Z",
    born_place: {
      departamento: "Arequipa",
      ciudad: "Arequipa",
    },
    isRural: false,
    cedula: 98765432,
    phone: "555-101-1122",
    references: [
      {
        name: "Carlos Rojas",
        phone: "555-202-2233",
        relationship: "Hermano",
      },
    ],
    marital_status: "Soltera",
    direction: {
      street: "Av. Los Pinos 45",
      zone: "Este",
      city: "Arequipa",
    },
    adiccions: [
      {
        name: "Videojuegos",
        consumption_time: "5 años",
      },
    ],
    education: {
      primary: true,
      secondary: true,
      university: true,
    },
    profession: "Ingeniera",
    ocupation: "Desarrolladora",
    talents: ["Dibujo digital", "Programación"],
    guarantor_name: null,
    image: null,
    user_id: "user126",
    interned_at: "2023-06-20T09:00:00.000Z",
    out_at: "2023-08-01T14:00:00.000Z",
    status: "Inactivo",
    finished_program: true,
    out_properties: {
      reason: "Finalización exitosa",
      observations: "Alta recomendada tras cumplir objetivos.",
    },
  },
  {
    id: "clx2a3b4c56d9",
    created_at: "2024-03-10T13:15:00.000Z",
    name: "Jorge Hidalgo",
    birthdate: "1982-08-10T00:00:00.000Z",
    born_place: {
      departamento: "Puno",
      ciudad: "Juliaca",
    },
    isRural: true,
    cedula: 56473829,
    phone: "555-555-1234",
    references: [
      {
        name: "Luz Hidalgo",
        phone: "555-444-5678",
        relationship: "Esposa",
      },
    ],
    marital_status: "Casado",
    direction: {
      street: "Jr. Comercio 23",
      zone: "Oeste",
      city: "Juliaca",
    },
    adiccions: [],
    education: {
      primary: true,
      secondary: true,
      university: false,
    },
    profession: "Chofer",
    ocupation: "Transportista",
    talents: ["Reparación de vehículos", "Oratoria"],
    guarantor_name: "Roberto Hidalgo",
    image: null,
    user_id: "user127",
    interned_at: "2024-03-15T08:00:00.000Z",
    out_at: null,
    status: "Activo",
    finished_program: false,
    out_properties: null,
  },
  {
    id: "clx2a3b4c56e0",
    created_at: "2022-11-20T16:00:00.000Z",
    name: "Lucía Fernández",
    birthdate: "2001-01-25T00:00:00.000Z",
    born_place: {
      departamento: "La Libertad",
      ciudad: "Trujillo",
    },
    isRural: false,
    cedula: 34567890,
    phone: "555-789-4561",
    references: [
      {
        name: "Julio Fernández",
        phone: "555-987-6541",
        relationship: "Padre",
      },
    ],
    marital_status: "Soltera",
    direction: {
      street: "Pasaje Los Olivos 14",
      zone: "Sur",
      city: "Trujillo",
    },
    adiccions: [
      {
        name: "Redes Sociales",
        consumption_time: "2 años",
      },
    ],
    education: {
      primary: true,
      secondary: true,
      university: false,
    },
    profession: null,
    ocupation: null,
    talents: ["Canto", "Danza"],
    guarantor_name: "María Fernández",
    image: null,
    user_id: "user128",
    interned_at: "2022-11-25T12:00:00.000Z",
    out_at: "2023-01-10T16:00:00.000Z",
    status: "Inactivo",
    finished_program: true,
    out_properties: {
      reason: "Alta médica",
      observations: "Recomendación de seguimiento externo.",
    },
  },
];

export const FAKE_HISTORY = [
  {
    id: 1,
    created_at: "2025-01-06T10:15:00.000Z",
    intern_id: "clx1y2z3a45b6",
    notes: "El paciente ha mostrado progreso en las sesiones iniciales.",
    user_id: "user123",
  },
  {
    id: 2,
    created_at: "2025-01-12T15:45:00.000Z",
    intern_id: "clx1y2z3a45b7",
    notes: "El paciente ha participado activamente en talleres grupales.",
    user_id: "user124",
  },
];
